### ISSUE TITLE
Resolve the internal library issue for stackage

### ISSUE THREAD

**Issue by toku-sa-n** [mihaimaruseac/hindent#755] opened 2023-06-17 00:13 UTC
See https://github.com/commercialhaskell/stackage/issues/6982.

**Comment by mihaimaruseac** [comment] 2023-06-17 17:38
The issue is mostly on stack, we can remove the internal library from `hindent` if we don't want to wait for a Stack fix.

I need to find my notes from nearly 3 years ago about the Stack build process and the internal libraries issues

**Comment by mihaimaruseac** [comment] 2023-06-26 15:39
For now this is resolved by https://github.com/commercialhaskell/stackage/commit/f47d9b339eff28771c0ffbd305d22ddf7a44d2b0

**Closed by mihaimaruseac** 2023-06-26 15:39 UTC
